title: Help | Cloud 66
email: support@cloud66.com
permalink: /:collection/:path/

collections:
  legacy_docker:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  maestro:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  node:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  rails:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  skycap:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  habitus:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  starter:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  copper:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  alterant:
    output: true
    permalink: /:collection/:path/
    icon: foundicon-idea
  redirects:
    output: true
    permalink: /:path/
# Build settings
markdown: kramdown

sass:
    style:  compressed  # nested|expanded|compact|compressed

safe: false

defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect

url: https://help.cloud66.com

plugins:
  - jekyll-sitemap
